### ISSUE TITLE
[Feature] 规范化文档

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#111]
由于前期项目未整合，文件夹有些紊乱，特此规定如下：
---
**题目描述文件** ：PAT-B1001.害死人不偿命的(3 * n + 1)猜想.md
**C++**：PAT-B1001.害死人不偿命的(3 * n + 1)猜想.cpp
**Java**：PAT-B1001.害死人不偿命的(3 * n + 1)猜想.java
---
其他的以此类推

**Comment by freedom3219** [comment]
我来负责 Java 文件的规范

**Comment by Galaxy-Hitchhiker** [comment]
那我来负责题目描述文件和c++文件

**Comment by QuakeWang** [comment]
> 那我来负责题目描述文件和c++文件

再修改题目描述文件的时候 还应注意 md 文件中，标题名统一

**Comment by Galaxy-Hitchhiker** [comment]
> > 那我来负责转型描述文件和c ++文件
> 
> 再修改修订描述文件的时候还应注意md文件中，标题名统一

OK

**Comment by QuakeWang** [comment]
good job @Galaxy-Hitchhiker ，
题目描述文件和 C++ 文件已经完成 #113

**Comment by QuakeWang** [comment]
well done @freedom3219 
Java 文件已完成 #114
