### ISSUE TITLE
[Add Question] 增加 PAT-B1027.打印沙漏 题目描述文件

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#124]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：**  打印沙漏
* **题目来源：**  https://pintia.cn/problem-sets/994805260223102976/problems/994805294251491328
* **提交路径：**  `PAT/题目描述文件/`
* **题目归类：** PAT-B

**Comment by glyco99** [comment]
我申请认领这个任务，用 C++ 编写

**Comment by glyco99** [comment]
我来提交这个题目描述文件
