### ISSUE TITLE
[Add Question] 增加 PAT-B1002.写出这个数 题目描述文件

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#125]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：**  写出这个数
* **题目来源：**  https://pintia.cn/problem-sets/994805260223102976/problems/994805324509200384
* **提交路径：**  `PAT/题目描述文件`
* **题目归类：** PAT-B
* **题解思路：**

**Comment by glyco99** [comment]
我申请提交这个题目描述文件信息
