### ISSUE TITLE
[Solution] 增加 PAT-B1002.写出这个数 题目解法

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#132]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：**  PAT-B1002.写出这个数
* **题目来源：**  https://pintia.cn/problem-sets/994805260223102976/problems/994805324509200384
* **提交路径：** `KO--CSP/PAT/cSrc/` `KO--CSP/PAT/javaSrc/`
* **题目归类：** PAT-B

**Comment by glyco99** [comment]
我用 C 来编写这道题

**Comment by QuakeWang** [comment]
> 我用 C 来编写这道题

赞！保持输出

**Comment by glyco99** [comment]
/*此程序在PAT中调用gcc/g++运行时会产生warning,而调用clang运行则正常显示，这是因为两者的编译规则有些不同。
    但程序整体逻辑是正确，在vscode等都可以成功运行调试*/

**Comment by freedom3219** [comment]
我用 Java 写
