### ISSUE TITLE
[Add Question] 完善 PAT-B 系列 前30题 题目描述文件

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#133]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目来源：**  https://pintia.cn/problem-sets/994805260223102976/problems/type/7
* **提交路径：** `PAT/题目描述文件/`
* **题目归类：**  PAT-B

**Comment by QuakeWang** [comment]
#145 PAT-B1006 已提交

**Comment by QuakeWang** [comment]
> /self-assign

good job！
可以先把还缺的题目留个 comment ^_^

**Comment by JaydenHD** [comment]
> > /自我分配
> 
> 干得好！
> 可以先把还缺的题目留个评论^_^

copy that

**Comment by QuakeWang** [comment]
> > > /自我分配
> 
> > 
> 
> > 干得好！
> 
> > 可以先把还缺的题目留个评论^_^
> 
> 
> 
> copy that

What's this??

**Comment by JaydenHD** [comment]
> > > > /自我分配
> > 
> > 
> > > 
> > 
> > 
> > > 干得好！
> > 
> > 
> > > 可以先把还缺的题目留个评论^_^
> > 
> > 
> > copy that
> 
> What's this ??

收到！^_^

**Comment by JaydenHD** [comment]
截至目前，不出意外的话，还有B1023跟B1027两个题目描述文件没有人认领

**Comment by QuakeWang** [comment]
> 截至目前，不出意外的话，还有B1023跟B1027两个题目描述文件没有人认领

Ok, you can do this!

**Comment by JaydenHD** [comment]
> > 截至目前，不出意外的话，还有B1023跟B1027两个题目描述文件没有人认领
> 
> Ok, you can do this!

okay I did it recently

**Comment by JaydenHD** [comment]
> > 截至目前，不出意外的话，还有B1023跟B1027两个题目描述文件没有人认领
> 
> Ok, you can do this!

okay I do it recently

**Comment by QuakeWang** [comment]
Thanks for @freedom3219 @glyco99 and @JaydenHD
