### ISSUE TITLE
[Add Question] 增加 PAT-B1006.换个格式输出整数 题目描述文件

### ISSUE THREAD

**Issue by glyco99** [OS-EDU/KO--CSP#143]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：**  换个格式输出整数
* **题目来源：**  https://pintia.cn/problem-sets/994805260223102976/problems/994805318855278592
* **提交路径：**  ` PAT/题目描述/ `
* **题目归类：**  PAT-B

**Comment by QuakeWang** [comment]
请根据 #133 提交 PR 即可，不要过多的 issue
