### ISSUE TITLE
[Add Questions] 增加B1001题目描述

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#24]
增加B1001至[题目描述](https://github.com/OS-EDU/KO--CSP/tree/main/%E9%A2%98%E7%9B%AE%E6%8F%8F%E8%BF%B0)文件夹下

**Comment by freedom3219** [comment]
已增加B1001至题目描述文件夹下，pr如下:[增加B1001题目描述](https://github.com/OS-EDU/KO--CSP/pull/26)

**Comment by QuakeWang** [comment]
棒：）
