### ISSUE TITLE
OS-EDU公众号推送跟踪

### ISSUE THREAD

**Issue by Galaxy-Hitchhiker** [OS-EDU/KO--CSP#25]
OS-EDU公众号第一次推送[关于我们的OS-EDU](https://mp.weixin.qq.com/s/7thCgIdrtUUHeS2HGLkvvg)

**Comment by QuakeWang** [comment]
这个issue发错了项目地址，应该发在[os-edu.github.io](https://github.com/OS-EDU/os-edu.github.io/issues)
