### ISSUE TITLE
[Add Questions] 增加B1011题目描述

### ISSUE THREAD

**Issue by glyco99** [OS-EDU/KO--CSP#33]
# B1011
 ## 题目描述：
 * 给定区间[-2^31, 2^31]内的三个正整数A、B和C，请判断 A + B 是否大于 C
 ## 输入格式：
 * 第一行给出正整数T（T <= 10），即测试用例的个数。随后给出T组测试用例，每组
 * 占一行，顺序给出A、B和C。整数间以空格分隔。
 * 输出格式：
 * 对每组测试用例，如果A + B > C，在一行中输出“Case #X: true”；否则给出
 * “Case #X: false”，其中X是测试用例的编号（从1开始）。
 ## 输入样例：
 * 4
 * 1 2 3
 * 2 3 4
 * 2147483647 0 2147483646
 * 0 -2147483648 -2147483647
 * 输出样例：
 * Case #1: false
 * Case #2: true
 * Case #3: true
 * Case #4: false
 */

**Comment by G-lyco** [comment]
增加B1011题目描述

**Comment by QuakeWang** [comment]
可以提交相关的pr至[题目描述](https://github.com/OS-EDU/KO--CSP/tree/main/%E9%A2%98%E7%9B%AE%E6%8F%8F%E8%BF%B0)文件夹下

**Comment by freedom3219** [comment]
我来帮高老师提交B1011题目描述的pr吧！

**Comment by QuakeWang** [comment]
需要把文件调到指定分支下 [题目描述](https://github.com/OS-EDU/KO--CSP/tree/%E9%A2%98%E7%9B%AE%E6%8F%8F%E8%BF%B0)

**Comment by QuakeWang** [comment]
#37 B1011题目描述文件已提交
