### ISSUE TITLE
增加PAT-B1012 C语言解法

### ISSUE THREAD

**Issue by freedom3219** [OS-EDU/KO--CSP#53]
在KO--CSP的csource中暂无PAT-B012的题解，所以我想来解答它。

**Comment by QuakeWang** [comment]
棒！:)

**Comment by freedom3219** [comment]
在我看PAT-B1012题目描述的过程中，发现B1012题目描述存在一些错误

**Comment by QuakeWang** [comment]
> 在我看PAT-B1012题目描述的过程中，发现B1012题目描述存在一些错误

欢迎指出错误的所在之处

**Comment by freedom3219** [comment]
发现题目中的一些Bug，明天再改
