### ISSUE TITLE
[Add Question]添加 PAT_B.1036 跟奥巴马一起编程 题目描述文件

### ISSUE THREAD

**Issue by QuakeWang** [OS-EDU/KO--CSP#84]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：**  PAT-B.1036 跟奥巴马一起编程
* **题目来源：**  https://pintia.cn/problem-sets/994805260223102976/problems/994805285812551680
* **提交路径：**  `KO--CSP/PAT/题目描述/`
* **题目归类：** PAT-B

**Comment by GuaPiMa** [comment]
添加 PAT_B.1036 跟奥巴马一起编程 题目描述文件

**Comment by QuakeWang** [comment]
感谢 @GuaPiMa ，题目描述文件已提交 #85
