### ISSUE TITLE
[Add Question] 增加PAT-B1022.D进制的A+B 题目描述

### ISSUE THREAD

**Issue by freedom3219** [OS-EDU/KO--CSP#86]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：** PAT-B1022.D进制的A+B 
* **题目来源：** https://pintia.cn/problem-sets/994805260223102976/problems/994805299301433344
* **提交路径：** KO--CSP/PAT/题目描述/
* **题目归类：** PAT-B

**Comment by QuakeWang** [comment]
> ## 参与必读！！！
> * **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/
> 
> ## 添加题目
> * **题目名称：** PAT-B1022.D进制的A+B
> * **题目来源：** https://pintia.cn/problem-sets/994805260223102976/problems/994805299301433344
> * **提交路径：**  `KO--CSP/PAT/题目描述/`
> * **题目归类：** PAT-B

建议路径使用代码块，防止路径出错

**Comment by freedom3219** [comment]
题目描述已发布[#94](https://github.com/OS-EDU/KO--CSP/pull/94)
