### ISSUE TITLE
[Add Question]添加 PAT_B1030.完美数列 题目描述文件

### ISSUE THREAD

**Issue by GuaPiMa** [OS-EDU/KO--CSP#93]
## 参与必读！！！

* **贡献指南：** https://os-edu.github.io/contribution/add_contributing_guide/

## 添加题目

* **题目名称：** PAT-B1030.完美数列
* **题目来源：** https://pintia.cn/problem-sets/994805260223102976/problems/994805291311284224
* **提交路径：** `KO--CSP/PAT/题目描述/`
* **题目归类：** PAT-B

**Comment by QuakeWang** [comment]
#88 已提交。
